version: '3'

services:
  build:
    container_name: build
    image: matfin/cinematt-build:latest
    build:
      context: .
      dockerfile: .docker/next/Dockerfile
    volumes:
      - static-content:/opt/build/out

  serve:
    container_name: serve
    image: matfin/cinematt-serve:latest
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_HOST=cinematt.build
      - SSL_CERTIFICATE=server.crt
      - SSL_CERTIFICATE_KEY=server.key
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/ssl/letsencrypt:/etc/letsencrypt:ro
      - static-content:/opt/public
    command: nginx -g "daemon off;"

volumes:
  static-content:
